# Data Getting

In [20]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv('data/raw.csv')


In [22]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Encoding

In [41]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = label_encoder.fit_transform(df[col])
        
df.head()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602     1115          619          0       0   42   
1          2    15647311     1177          608          2       0   41   
2          3    15619304     2040          502          0       0   42   
3          4    15701354      289          699          0       0   39   
4          5    15737888     1822          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Feature Selection 

In [24]:
y = df['Exited']
col = ["Exited","RowNumber"]
X = df.drop(columns=col)

In [25]:
X.head()

CustomerId  Surname  CreditScore  Geography  Gender  Age  Tenure  \
0    15634602     1115          619          0       0   42       2   
1    15647311     1177          608          2       0   41       1   
2    15619304     2040          502          0       0   42       8   
3    15701354      289          699          0       0   39       1   
4    15737888     1822          850          2       0   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0       0.00              1          1               1        101348.88  
1   83807.86              1          0               1        112542.58  
2  159660.80              3          1               0        113931.57  
3       0.00              2          0               0         93826.63  
4  125510.82              1          1               1         79084.10

# Standardization

In [26]:
X = np.array(X)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(X)
X

array([[1.5634602e+07, 1.1150000e+03, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [1.5647311e+07, 1.1770000e+03, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.5619304e+07, 2.0400000e+03, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.5584532e+07, 1.5700000e+03, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.5682355e+07, 2.3450000e+03, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.5628319e+07, 2.7510000e+03, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [27]:
X.shape

(10000, 12)

# Train Test Split

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((8000, 12), (2000, 12))

# Applying the Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
print(model.score(X_test,y_test)*100,"%")

80.35 %


c:\Users\ST\Desktop\mldeployement\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Evaluation of Model

In [37]:
from sklearn.metrics import confusion_matrix
y_pred =  model.predict(X_test)
print(y_pred)
cm = confusion_matrix(y_pred=y_pred,y_true=y_test)
cm

[0 0 0 ... 0 0 0]


array([[1607,    0],
       [ 393,    0]], dtype=int64)

In [31]:
from sklearn.metrics import mean_absolute_error
mbe = mean_absolute_error(y_pred,y_test)
mbe

0.1965

In [34]:
pred_df = pd.DataFrame({'Actual':y_test,'predicted':y_pred,'Difference':(y_test-y_pred)})
pred_df

Actual  predicted  Difference
6252       0          0           0
4684       0          0           0
1731       0          0           0
4742       0          0           0
4521       0          0           0
...      ...        ...         ...
6412       1          0           1
8285       0          0           0
7853       1          0           1
1095       1          0           1
6929       1          0           1

[2000 rows x 3 columns]

In [46]:
for col in df.columns:
    if df[col].dtype=='object':
        print(col)



Surname
Geography
Gender
